### ISSUE TITLE
Requesting multiple types respond with less links than requesting each types separately

### ISSUE THREAD

**Issue by enwin** [aaronpk/webmention.io#100]
Hi,

I'm currently implementing webmention on my domain (https://switch.paris) and when fetching webmentions using the token I get inconsistencies in the number of links sent back.

Getting the replies:
`https://webmention.io/api/mentions?token=XXXX&wm-property=in-reply-to` responds with 4 links

Getting the mentions:
`https://webmention.io/api/mentions?token=XXXX&wm-property=mention-of` responds with 2 links

Combining the two: 
`https://webmention.io/api/mentions?token=XXXX&wm-property[]=in-reply-to&wm-property[]=mention-of` responds with 2 links (the mentions), I'm expecting the response to contains 6 links

Interestingly enough, when reversing the order of the types queried:
`https://webmention.io/api/mentions?token=XXXX&wm-property[]=mention-of&wm-property[]=in-reply-to` responds with 0 links

So far, all webmentions comes from twitter using https://brid.gy.

Am I doing something wrong?

Thanks for your feedback and for this platform :)

**Comment by aaronpk** [comment]
I fixed the problem with ordering the parameters in de1158824d6270f51526807110e85b0ac4b3e45f

This should all be resolved now.
