### ISSUE TITLE
Limit on the number of webmentions reported by webmentions.io?

### ISSUE THREAD

**Issue by kaushalmodi** [aaronpk/webmention.io#105]
Hello,

I am working on indiewebifying my blog scripter.co. 

I believe I have most of the pieces together. 

I am working on the last part where I show the received mentions for a post under that post.. and eventually get rid of Disqus. 

While testing this out, I see that the list of webmentions received through webmention.io is a lot smaller than those sent by brid.gy (only mentions through Twitter). It looks like webmention.io does not send older mentions via the API, or has a limit on number of links in that JSON object?

Example: Number of likes on a [post tweet][1] is 53, but the number I derive through the count of links with "like" activity type in the JSON object is 10 (scroll to the bottom of [this demo page][2]). 

For reference, this is [how I parse the JSON][3] using the Hugo Go templating. 

[1]: https://twitter.com/kaushalmodi/status/975860854573936640
[2]: https://wm--scripter-co.netlify.com/git-diff-minified-js-and-css/
[3]: https://gitlab.com/kaushalmodi/hugo-theme-refined/blob/master/layouts/partials/webmention_rcv.html

**Comment by aaronpk** [comment]
Did you try using the paging and limit parameters in the API? 

https://github.com/aaronpk/webmention.io#paging

**Comment by kaushalmodi** [comment]
Thank you! Later today, I'll try with a higher page item count of 200. Though, I am retrieving this JSON at site build time. So is there an option of *infinite*, so that all possible mentions get retrieved?

**Comment by kaushalmodi** [comment]
Basically, I don't need "pages" as I am parsing the whole JSON object. I am just looking for a way to get *all* mentions for a given post, without worrying about pages.

**Comment by kaushalmodi** [comment]
Hello,

Just confirming one more thing about the retrieved mentions using your API.

Doing `https://webmention.io/api/count?jsonp&target=https://scripter.co/git-diff-minified-js-and-css/`, I get:

```json
{
  "count": 51,
  "type": {
    "like": 24,                                <----------
    "mention": 3,
    "reply": 4,
    "repost": 20                               <----------
  }
}
```

But the actual likes/retweets are 53/21. Does that mean that brid.gy somehow was unable to catch the likes/retweets completely?

**Comment by kaushalmodi** [comment]
Thanks! I now understand why the likes/reposts count is not accurate.. but that's OK.. the replies are more important, and they seem to come through fine! Thanks for your prompt replies :)
