### ISSUE TITLE
Salmention support

### ISSUE THREAD

**Issue by EdwardHinkle** [aaronpk/webmention.io#112]
Does Webmention.io support Salmention? Or is it expected of a Webmention.io user that they fetch the responses on the mentioning post by manually fetching the post information when they receive the webmention.io ping?

(Originally published at: https://eddiehinkle.com/2018/07/23/18/reply/)

**Comment by aaronpk** [comment]
No plans for Salmention support right now, this will require further consideration for how a service like webmention.io can be in the middle of Salmention handling https://indieweb.org/Salmention#Receiving_Salmentions
