### ISSUE TITLE
webmention.io/js/mentions.js not working

### ISSUE THREAD

**Issue by vikanezrimaya** [aaronpk/webmention.io#116]
Hello. I'm currently using webmention.io to receive WebMentions for my blog, and it works. With a lot of hackery, as the by-the-book example didn't work.

**Disclaimer**: I'm no JS developer, so I ask anyone who will be reading this resist the urge to wrench off my hands so I could not code any more.

I wanted to make mention counter display under each post in the list, and the example on the site (with a JS file include) didn't work - seems like API changed. It got me 400 error and said that I need to provide "target" parameter.

I use Hugo to generate my website and next code I wrote contains a bit of Go templates:
```
      <p class="list-mentions">
      <span data-webmention-count id="{{ .Permalink }}"><script>
        $.getJSON("https://webmention.io/api/count?jsonp=?", {
          target: "{{ .Permalink }}"
        }, function(data) {
          document.getElementById("{{ .Permalink }}").innerHTML = data.count;
        });
      </script></span> mentions
      </p>
```

It works. But if I start to be popular, I'm afraid I'll flood your server. This snippet repeats for every post in a list - three times in a page.

**Comment by kaushalmodi** [comment]
@kisik21 I have been receiving Webmentions from webmention.io for quite some time now on my blog, Hugo generated as well.

See if this code helps you: https://gitlab.com/kaushalmodi/hugo-theme-refined/blob/96d571b7b9ef6ca81b6f8d833e78a39912aef08c/layouts/partials/webmention_rcv.html#L17.

**Comment by kisik21** [comment]
@kaushalmodi so, these are static comments pulled from webmentions on each site rebuild?

It is cool, but I'm more used to real-time interactive stuff. That's why I'm actually using JS. And there seems to be no way to pull counters for each post on one request - which is why I'm actually doing this stuff with one request per post, which I think is inefficient.

**Comment by kaushalmodi** [comment]
> these are static comments pulled from webmentions on each site rebuild?

Yes.

> It is cool, but I'm more used to real-time interactive stuff. That's why I'm actually using JS. 

There's an inbuilt magic in my setup; it's not as interactive as JS, but it kind of *is* interactive.

I do this:

![image](https://user-images.githubusercontent.com/3578197/48224118-e0a6d780-e366-11e8-8b6b-ef63fa53a867.png)

> And there seems to be no way to pull counters for each post on one request 
> - which is why I'm actually doing this stuff with one request per post, which I think is inefficient.

You would pull the JSON payload for each post and count the number of entries in each. Yes, there doesn't seem to be a way to tell webmention.io that give me *all* webmentions for this URL, but you can specify an upper bound. I don't expect any of my posts to have more than 200 mentions (arbitrary number based on my experience), so I tell wm.io to give me up to 200 mentions for every URL.

Hugo has excellent and fast JSON/data parsing baked in. Using that, you can get the count, etc.

It's not very efficient to pull in mentions for each post one at a time, but the whole site builds in about 5 seconds for me.


> My setup can be seen on https://fireburn.ru - just look at these counters, aren't they pretty?

They sure are :) What I am getting at is that you can do that without JS too. I do it. Here's another example where you can see the counts: https://scripter.co/splitting-an-org-block-into-two/#webmentions

I chose to hide the counts if 0, and I count only. Source is in that same `webmention_rcv.html` that I linked earlier.
