### ISSUE TITLE
Feature request: Add support for follow posts

### ISSUE THREAD

**Issue by EdwardHinkle** [aaronpk/webmention.io#117]
I opened an issue on xray to support Follow posts (https://github.com/aaronpk/XRay/issues/81), but it turns out xray supports follow posts (http://xray.p3k.io/parse?url=https%3A%2F%2Ffed.brid.gy%2Frender%3Fsource%3Dhttps%253A%252F%252Fmastodon.technology%252Fdf9fe479-7dfd-495c-9f13-7dad2910e813%26target%3Dhttps%253A%252F%252Feddiehinkle.com%252F&pretty=true) it's webmention.io that doesn't support follow posts.

That post turns into the following on webmention.io, it should be a follow post:
```json
{
      "type": "entry",
      "author": {
        "type": "card",
        "name": "Ryan Barrett",
        "photo": "https://webmention.io/avatar/static.mastodon.technology/17d9c9f06718a305b395f9148ca41e3d13e045d97cbb38021d6d14e07ee8f8e1.png",
        "url": "https://mastodon.technology/@snarfed"
      },
      "url": "https://fed.brid.gy/render?source=https%3A%2F%2Fmastodon.technology%2Fdf9fe479-7dfd-495c-9f13-7dad2910e813&target=https%3A%2F%2Feddiehinkle.com%2F",
      "published": null,
      "wm-received": "2018-11-13T22:03:50Z",
      "wm-id": 562293,
      "mention-of": "https://eddiehinkle.com/",
      "wm-property": "mention-of",
      "wm-private": false
    }
```

**Comment by EdwardHinkle** [comment]
Some documentation from the original xray issue:

An example of mf2 from Bridgy Fed: https://pin13.net/mf2/?url=https%3A%2F%2Ffed.brid.gy%2Frender%3Fsource%3Dhttps%3A%2F%2Ftoot.cafe%2F3d36ccca-de8a-4d5b-b1bc-0be967c2b663%26target%3Dhttps%3A%2F%2Fsnarfed.org%2F

Based on the documentation here: https://indieweb.org/follow

**Comment by fluffy-critter** [comment]
I would also like to see `u-follow-of` implemented, as I am also using fed.brid.gy. Would it be possible/sensible for `wm-property` to automatically fall back to the first `u-*` type if there's no recognized types found, so that any future mf2 link types may be supported automatically?

**Comment by aaronpk** [comment]
It's not clear that Follow posts have gained any traction, closing this for now, but feel free to reopen or file a new issue for this in the future.
