### ISSUE TITLE
Tag: My Favorites from JSON Webmention.io

### ISSUE THREAD

**Issue by noorlutfiyahafifah** [aaronpk/webmention.io#119]
When I like the post "[Sending your First Webmention from Scratch](https://aaronparecki.com/2018/06/30/11/your-first-webmention)" from the [aaronparecki.com](https://aaronparecki.com) website, can I retrieve JSON data from my blog [noorlutfiyahafifah.blogspot.com](https://noorlutfiyahafifah.blogspot.com/) to get a post that I like? So, with that, I will make the "My Favorites" tag in my blog with that data.

**Comment by aaronpk** [comment]
That sounds like a feature request for your blog, not for webmention.io. In your example, aaronparecki.com uses webmention.io to receive webmentions sent to it, which may come from any number of sites, not just yours.
