### ISSUE TITLE
Document /api/count.json endpoint

### ISSUE THREAD

**Issue by mxstbr** [aaronpk/webmention.io#120]
Rendering like and response counts is a pretty common UI pattern on blogs, for example:

![screen shot 2019-01-16 at 14 33 49](https://user-images.githubusercontent.com/7525670/51252304-c3f8d280-199b-11e9-8e5d-b308f05c3ff6.png)

Right now, to render the counts I have to fetch all pages of webmentions, even if I don't want to show the actual webmentions until the person clicks on the "XYZ responses", nevermind paginating them.

It would be awesome if the API had an endpoint to get the counts of mentions per type for a specific page, for example I imagine something like this:

```sh
$ curl https://webmentions.io/api/mention-counts.jf2?target=bla.com
{
  "like-of": 295,
  "in-reply-to": 33,
  "repost-of": "186,
  "mention-of": 41,
  "bookmark-of": 11
}
```

**Comment by aaronpk** [comment]
It's already there, just apparently not in the readme! The endpoint is /api/count.json

**Comment by aaronpk** [comment]
This has been added to the home page for some time now

https://webmention.io/#display-mention-counter
