### ISSUE TITLE
Bare domain or subdomains when signing up

### ISSUE THREAD

**Issue by RickCogley** [aaronpk/webmention.io#121]
Hello - first time trier of webmentions, here. When I sign up, do I use my bare domain (me.com) or, do I sign up multiple times using each subdomain I'm using (www.me.com, other.me.com)? I have a couple sites I would like to use webmentions with. --Rick

**Comment by aaronpk** [comment]
You can sign in with one account and then use that on a bunch of domains. The account you log in with is just used to create the webmention endpoint and to give you access to the dashboard.

**Comment by RickCogley** [comment]
Hi @aaronpk thanks! Appreciate the quick response!
