### ISSUE TITLE
Webmention.io /api target= param should accept protocol relative URL to return http + https...

### ISSUE THREAD

**Issue by tantek** [aaronpk/webmention.io#122]
The webmention.io /api endpoints accept a 'target' query parameter which currently must be an absolute URL. This proposal extends the 'target' query parameter to also accept a protocol relative URL (i.e. starting with "//") and return all mentions of that target with any protocol (e.g. both 'http:' and 'https:').

Use-case: this will allow sites which have migrated from http to https, or which still serve both http and https and accept webmentions for both, to easily query webmention.io for all mentions to either http/https versions of their permalinks, to show webmentions regardless of which protocol was used in their webmention target URLs.

Test-case: http://tantek.com/2019/065/e1/homebrew-website-club-sf is live with an iframe that embeds a display of RSVP webmentions via a service using a protocol relative URL in the target param to a webmention.io api call. Check both of these:

  * [http://tantek.com/2019/065/e1/homebrew-website-club-sf](http://tantek.com/2019/065/e1/homebrew-website-club-sf)
  * [https://tantek.com/2019/065/e1/homebrew-website-club-sf](https://tantek.com/2019/065/e1/homebrew-website-club-sf)

And you should see at least one RSVP displayed in the bottom from v2.jacky.wtf, likely with a green checkmark ✅. Here’s a direct link to just the RSVP display for that post but hardcoded to 'http:' mentions only: [v2.jacky.wtf RSVP](https://stream.thatmustbe.us/?url=https%3A%2F%2Fwebmention.io%2Fapi%2Fmentions.jf2%3Fwm-property%3Drsvp%26sort-by%3Drsvp%26target%3Dhttp%3A%2F%2Ftantek.com%2F2019%2F065%2Fe1%2Fhomebrew-website-club-sf&op=jf2-mf2&ashtml=1&style=img{height:44px;vertical-align:bottom}.h-feed%3E.p-name,.h-entry%3E.u-url:first-child,.h-entry%3E.p-name,.u-url%3E.p-name,.p-in-reply-to,.p-like-of,.p-mention-of,*[class^=p-wm-],.dt-published,.p-syndication{display:none}.h-card{float:left;border:solid%201px%20%23999;margin:0%202px%202px%200;line-height:44px}.p-rsvp:before{content:%22%E2%98%85%22;float:left;color:white;background:blue;font-size:10px;line-height:1.5;width:13px;height:13px;text-align:center;margin:35px%200%20-3px%20-14px;border-radius:3px;position:relative;z-index:1}.p-rsvp[value=yes]:before{content:%22%E2%9C%85%22;font-size:13px;margin:34px%200%20-3px%20-16px;background:none}.p-rsvp[value=no]:before{content:%22%E2%9D%8C%22;background:white;color:red;font-size:13px}body{margin:0}img[src=%22%22]{width:0.6em}). 

(Originally published at: https://tantek.com/2019/065/b1/webmention-io-target-accept-protocol-relative-url)

**Comment by aaronpk** [comment]
Protocol-relative URLs work now!
