### ISSUE TITLE
Internal Server Error on login

### ISSUE THREAD

**Issue by Ryuno-Ki** [aaronpk/webmention.io#124]
When logging in on webmention.io using GitHub or Twitter, I'll get a 500 Internal Server Error as soon as I end back on the website (that is, IndieAuth seem to work).

**Comment by jasonrbriggs** [comment]
Also an issue for me with github and pgp.

**Comment by aaronpk** [comment]
Thanks for the bug reports! I just pushed a change that should fix this.

**Comment by jasonrbriggs** [comment]
Confirmed. Looks like it's working now, thanks.
