### ISSUE TITLE
400s on target/source URLs with escaped emoji chars

### ISSUE THREAD

**Issue by snarfed** [aaronpk/webmention.io#125]
example:

```sh
$ curl -v -d source=https://brid-gy.appspot.com/like/twitter/ChrisAldrich/1129124049068498944/14591484
  -d target=https://boffosocko.com/2019/04/29/%f0%9f%93%85-virtual-homebrew-website-club-meetup-on-may-15-2019/
  http://webmention.io/boffosocko.com/webmention
{"error":"invalid_request","error_description":"source or target were invalid"}
```

if you remove `%f0%9f%93%85` from the target URL, it works ok.

just fyi! not a high priority for me personally. cc @dshanske @chrisaldrich, inspired by https://github.com/snarfed/bridgy/issues/870

**Comment by aaronpk** [comment]
Not related to the underlying issue, but the URL on that bridgy page contains the escaped characters as lowercase, not uppercase in the curl command.

**Comment by snarfed** [comment]
oops, thanks! fixed.

**Comment by aaronpk** [comment]
weird, for some reason Sinatra is unescaping the URL by the time it's passed into the code, so the URI parser freaks out. I added an escape and that seems to have fixed it.
