### ISSUE TITLE
Are deletes (POST source has 410) supported?

### ISSUE THREAD

**Issue by remy** [aaronpk/webmention.io#127]
I sent a mention for a source that now give a 410 status and though webmention.io replied saying it was processed, the webmention was not deleted for the target.

Status URL: https://webmention.io/www.zachleat.com/webmention/1xAsicByB1PFYFPNE0zE

HEAD on the source:

```
$ curl -I https://remysharp.com/2019/06/10/ejecting-disqus

HTTP/1.1 410 Gone
Cache-Control: public, max-age=0, must-revalidate
Content-Length: 0
Content-Type: text/html; charset=UTF-8
Date: Wed, 12 Jun 2019 15:47:32 GMT
Etag: "fb0c5064c0ba75178c256d1c850a58c9-ssl"
Strict-Transport-Security: max-age=31536000
X-Powered-By: unicorns and kittens
Age: 0
Connection: keep-alive
Server: Netlify
```

**Comment by aaronpk** [comment]
410 deletes aren't yet supported, but they really should be!

I do see a regular 404 at that URL though, and then somehow a JavaScript redirect to the correct URL.

**Comment by remy** [comment]
Yeah, I pushed another change worrying that I was sending a 410 but still rendering the full content.

If you run the `curl` again, you'll get the 410 again and in the browser it'll then attempt to redirect to find the right page.

**Comment by remy** [comment]
If that's live on webmention.io, I'll give it a test using my original method (if you've not already) (on Monday though, father's Day tomorrow, attempting to be computer free!)

**Comment by aaronpk** [comment]
It's almost live as soon as I finish the deploy! Will comment back here soon.

**Comment by aaronpk** [comment]
Ok, it's live! I just tested it on my own site and it's working!
