### ISSUE TITLE
Orphaned webmentions

### ISSUE THREAD

**Issue by dmyates** [aaronpk/webmention.io#130]
I've run into a strange bug. When I initially signed into webmention.io using IndieAuth with my URL (https://davidyat.es) and Github, it gave me the username `davidyat.es_`, which I used for my first attempted setup. After doing that, I loaded in some webmentions through Bridgy and Checkmention, but they didn't show up anywhere in the interface.

I then logged out and in again, which changed my username to `davidyat.es`, and I changed the webmention setup on my site accordingly. After this I resent the Bridgy mentions, and they all showed up on the webmention.io interface. I've never been able to get that underscore to reappear.

However, as soon as I tried using the API to load mentions for individual pages, I noticed that Bridgy webmentions were duplicated, and the Checkmotion webmotions appeared for the first time. I then deleted all the webmentions in my webmotion.io interface, and was left with a number of webmotions that could be found by querying specific pages through the API but did not show up in my overall feed.

For example, this API call returns a number of webmentions for a specific page:

    GET https://webmention.io/api/mentions.jf2?target=https://davidyat.es/2019/02/03/review-unavowed/

But this API call returns nothing for the whole site:

    GET https://webmention.io/api/mentions.html?token=MY-TOKEN-HERE

I also cannot delete webmentions available from the API through the webmention.io interface. My best guess is that something funny happened with the auth process to give me two accounts, one of which I can't access.

**Comment by aaronpk** [comment]
wow, you seem to have run into a bug that was on the site for only about 45 minutes. When I was launching some recent changes the other day, webmention.io incorrectly assigned a username that ended in an underscore. That would only have mattered for people who logged in for the ~45 minute window that bug was live! I can move things around to restore the webmentions to your right account.

**Comment by aaronpk** [comment]
ok I cleaned things up. Should look better for you now.

**Comment by dmyates** [comment]
> wow, you seem to have run into a bug that was on the site for only about 45 minutes.

Just my luck. Everything seems in order now though. Thanks!

**Comment by dmyates** [comment]
Spoke a little too soon. Would you mind clearing my URL blacklists?

**Comment by aaronpk** [comment]
Sorry for the delay! Blacklists are cleared now.

**Comment by dmyates** [comment]
Thanks!
