### ISSUE TITLE
Web Hook Server Logs for Better Debugging

### ISSUE THREAD

**Issue by saulhardman** [aaronpk/webmention.io#134]
Hi @aaronpk,

In #69 you mention server logs relating to Web Hooks. I'm having trouble getting my configured Web Hook to trigger when new Webmentions are received and am wondering whether we could surface these logs in that view somehow? Otherwise, would you be able to check the logs for issues relating to the domain `viewsource.io`?

Thanks in advance 🤗

**Comment by aaronpk** [comment]
I think that reference to the logs was not about the web hooks, just about processing in general. While I could add some visibility of the web hook logs, I don't think it would be terribly useful, since most of the errors are going to happen before then anyway. Sorry!
