### ISSUE TITLE
Add number of results or pages to paginate in the response 

### ISSUE THREAD

**Issue by PaulKinlan** [aaronpk/webmention.io#141]
Following on from https://github.com/aaronpk/webmention.io/issues/46 (also thanks for creating this service)

I am using the https://webmention.io/api/mentions.jf2?domain=paul.kinlan.me&token=... API to get a list of all webmentions on my site, but I realised that I have to paginate the results to get them all, however I don't know how many pages I need to iterate over.

I tried to use https://webmention.io/api/count.json?target=paul.kinlan.me but it returns 0. One solution might be to include it in the response to the mentions.jf2

**Comment by PaulKinlan** [comment]
Actually, this is the same as https://github.com/aaronpk/webmention.io/issues/108

**Comment by rubenwardy** [comment]
> Actually, this is the same as #108

then close it?
