### ISSUE TITLE
500 when configuring Webhook Secret

### ISSUE THREAD

**Issue by jamietanna** [aaronpk/webmention.io#145]
When attempting to set up a shared secret for a webhook, I receive a 500 on clicking save. One solution was to generate a new, much shorter secret.

The secret that caused an error was:

```
930fe9263fb47891961a780f0569981daf595e81163d9ddb6d7ee0e037501f3d
```

But it appears to be others with the same length causing the same error. It appears that the limit is 50:

https://github.com/aaronpk/webmention.io/blob/master/models/site.rb#L16

Would it be possible to add some client-side validation of this, so it's a bit clearer to the user?

**Comment by aaronpk** [comment]
I added maxlength to the html attribute and truncate the value if you try to save a longer value
