### ISSUE TITLE
Questions regarding blacklist behaviour

### ISSUE THREAD

**Issue by Lucas-C** [aaronpk/webmention.io#146]
Hi.

I am working on a plugin for the [Pelican](https://getpelican.com) Python static blog generator, that will enable bloggers to send linkbacks: <https://github.com/pelican-plugins/linkbacks/>

So far, it supports classic pingbacks and webmentions.

Today in my latest tests, I tried creating a Pingback from <https://chezsoi.org/lucas/blog/> to <https://chezsoi.org/lucas/blog/pages/jeux-de-role.html>, expecting that my plugin would follow this link: `<link href="https://webmention.io/chezsoi.org_lucas_blog_/xmlrpc" rel="pingback"/>`.
The request got enqueued and then resulted in this error message: `source URL is blocked`.

From my understanding of this project Ruby code, on top of the per-user blocklist, there is a blacklist mechanism for the whole webmention.io website: https://github.com/aaronpk/webmention.io/blob/master/helpers/webmention_processor.rb#L90

Hence a couple of question:
- when & why is an URL blacklisted?
- how could <https://chezsoi.org/lucas/blog/> be removed from webmention.io blacklist ?

Regards

**Comment by aaronpk** [comment]
There is no global block list, it's always per user. In that code snippet, it searches the list for the URL in the context of that user's website.

If you delete a webmention from the dashboard view then it will block that URL from receiving webmentions in the future. I don't have a mechanism to un-block URLs right now, so I manually unblocked that particular URL for you.

**Comment by Lucas-C** [comment]
Alright! I understand now, thanks for the explanation.

As a side note, I thought it worked this way because the URL did not show up on my Blocklist: <https://webmention.io/settings/blocks>
Maybe, while keeping the current behaviour, the blocked URL from the deleted webmention whould appear in the user Blocklist ?

Thanks for your quick feedback anyway, feel free to close this issue.

**Comment by aaronpk** [comment]
ah I see the confusion! Yes that screen currently shows only the domains that are blocked, not individual URLs. I'll see what I can do to surface the individual URLs that are blocked.

**Comment by ivandokov** [comment]
Just want to +1 this as I got bitten by the same hidden blocked URL and I support the proposed solution to display the individual blocked URLs under Blocklist.

**Comment by ggirelli** [comment]
Same here. I ended up bumping my head against this issue :-/

**Comment by palol** [comment]
Ditto

**Comment by scientiac** [comment]
I have blocked (removed my link from the dashboard) myself while testing and now i cannot communicate with the site i set up for my friend. Is there an ability to unblock somehow?
