### ISSUE TITLE
Status: No Link Found - while the link is there

### ISSUE THREAD

**Issue by szpak** [aaronpk/webmention.io#150]
I've just found webmention.io and it looks really nice. Thanks for making that service!

However, I'm playing with it and I cannot create a test weblink using GET form for my blog.

The error I have:
![image](https://user-images.githubusercontent.com/148013/76088802-f1964600-5fb8-11ea-8b50-f7e90617bdf8.png)

However, the [link](https://blog.solidsoft.pl/2020/02/14/farewell-wordpress-bonjour-hugo/) is [there](https://solidsoft.wordpress.com/2020/02/27/farewell-wordpress-bonjour-hugo/):
![image](https://user-images.githubusercontent.com/148013/76088831-01ae2580-5fb9-11ea-955a-7a09ceda04f1.png)

I wonder, what could be wrong?

**Comment by szpak** [comment]
I looked into the source code for possible reasons, but even the summary message is not the same:
> The source document does not have a link to the target URL

vs
> The source URI does not contain a link to the target URI

existing [here](https://github.com/aaronpk/webmention.io/blob/master/controllers/webmention.rb#L109). I wonder if `webmention.io` uses the same version and/or what else could be done to make it work :-/.

**Comment by aaronpk** [comment]
This message is actually coming from [XRay](https://github.com/aaronpk/XRay), which is the one doing the link verification.

I see what's going on here. It's recognizing that the source document has Microformats, but that has some bad markup and is missing markup around the blog post contents. So it's not finding the link in the Microformats tree, so it's failing verification.

This is what it's seeing from the source document: https://php.microformats.io/?url=https%3A%2F%2Fsolidsoft.wordpress.com%2F2020%2F02%2F27%2Ffarewell-wordpress-bonjour-hugo%2F

I believe this is the correct behavior, so I'm going to improve the error message to make this clearer. Thanks!

**Comment by aaronpk** [comment]
Better error message: 

https://xray.p3k.app/parse?url=https%3A%2F%2Fsolidsoft.wordpress.com%2F2020%2F02%2F27%2Ffarewell-wordpress-bonjour-hugo%2F&target=https://blog.solidsoft.pl/2020/02/14/farewell-wordpress-bonjour-hugo/&pretty=true

**Comment by szpak** [comment]
Thanks that you looked into that.

The new error message is slightly more meaningful, but the reader still can be confused how to fix it. One of the articles found in the search engine is https://indieweb.org/microformats . It explains some things about the format, but for me not all.

The biggest problem I see, is the fact that all **not Microformats-compilant** pages cannot be used with webmention.io. It is unfortunate, as some referencing pages are served by hosted services. My old, referencing page is a good example - the free wordpress.com variant. I cannot add custom headers, nor freely transform HTML structure (adding classes).

Maybe I misunderstood your message, but is there a simple way to make my old Wordpress [page](https://solidsoft.wordpress.com/2020/02/27/farewell-wordpress-bonjour-hugo/) a valid source for webmention.io? If not, it greatly reduce the usage of your service (for pages similar to mine). Maybe in that case, XRay could make the second legacy fallback run to try to find the link anyway?

**Comment by aaronpk** [comment]
Okay, after further thought, I've changed how this works. Webmentions from pages with broken mf1 will now validate, however the page contents will not be returned since it isn't guaranteed to be able to find the link in the parsed contents.

**Comment by szpak** [comment]
It sounds sensible. Thanks for making it work also in those corner cases!
