### ISSUE TITLE
All test passed but webmentions doesn't appear in API

### ISSUE THREAD

**Issue by tcgumus** [aaronpk/webmention.io#151]
Hello, 
i have webmentions on my "dashboard" page but https://webmention.io/api/mentions.jf2?target=https://pikseladam.com link doesn't show some data. So, i can't display them on my web. What am I missing? Can you help me?

![image](https://user-images.githubusercontent.com/2714346/76576586-8e824300-64d3-11ea-9ebc-1b50f36f02a2.png)

![image](https://user-images.githubusercontent.com/2714346/76576596-993cd800-64d3-11ea-8146-393afbbe6578.png)

![image](https://user-images.githubusercontent.com/2714346/76576692-e15bfa80-64d3-11ea-8d75-a75521f74af9.png)

Thank you,
best regards,
tuna

**Comment by aaronpk** [comment]
Try using the method to retrieve all mentions of your domain:

https://github.com/aaronpk/webmention.io#find-all-links-to-your-domain

Or specify the exact url of a page to retrieve mentions for.

**Comment by tcgumus** [comment]
Thank you. I thought every value displayed in dashboard would be in the API results but target on main page is not listed. 👍
