### ISSUE TITLE
hosted service not showing all mentions? 

### ISSUE THREAD

**Issue by incanus** [aaronpk/webmention.io#158]
(I realize this is free, so I'm totally willing to help debug / get to the bottom of it the issue, if any, in the code). 

I'm using the hosted service in combination with Bridgy. For a recent post, the API is showing 50 likes/replies/etc., but there are more reported in Bridgy, and also reported to have sent mentions from there. They just don't show up in the API, feeds, dashboard, etc. 

I played with pagination of various sorts (though I was already using 100 per page, so it should have gotten all of them) including going down to small amounts like 5 and then stepping through. Every time, though, only the 57 come up. 

I also tried resending for the post through Bridgy, and after it worked its way through, still no dice. 

Any ideas?

**Comment by aaronpk** [comment]
I looked around a bit and I think I know what happened. The first clue was there were in fact exactly 57 responses in the database, so I know the API was returning the correct data.

When Bridgy sends the webmention, webmention.io queues it up for processing. webmention.io then fetches the page at bridgy to verify the webmention, which causes Bridgy to go fetch the tweet from Twitter.

If you click the timestamp on bridgy you'll get the bridgy log for when it sent that webmention, e.g:

https://brid.gy/log?start_time=1595019959&key=agdicmlkLWd5cjYLEghSZXNwb25zZSIodGFnOnR3aXR0ZXIuY29tLDIwMTM6MTI4Mzg1OTA4MTgzNzYzMzUzNgw

That will show what the webmention endpoint returned to Bridgy, in this case:

```
{"status":"queued","summary":"Webmention was queued for processing","location":"https://webmention.io/justinmiller.io/webmention/EO-QgB0n0XJpIhHBusBj","source":"https://brid-gy.appspot.com/comment/twitter/incanus77/1283837093618188289/1283859081837633536","target":"https://justinmiller.io/microposts/2020/07/16/1/"}
```

webmention.io returns a status URL that provides more info:

https://webmention.io/justinmiller.io/webmention/EO-QgB0n0XJpIhHBusBj

On that page it says `no_link_found`

I'm guessing what happened is there was a temporary failure trying to get the data from Twitter (maybe Bridgy was rate limited?) so the webmention failed.

Clicking retry on that webmention will make Bridgy send it again, and as long as it's not rate limited webmention.io will be able to fetch it again. I tried it on this one and I do see the comment now!

**Comment by incanus** [comment]
Awesome, thanks @aaronpk. Figured it was something like that. I'll retry and see what I can do.
