### ISSUE TITLE
Fetch webmention with ?domain is not working

### ISSUE THREAD

**Issue by Akashrine** [aaronpk/webmention.io#161]
Hello there ! 

I'm surely dumb but why does : 
https://webmention.io/api/mentions.jf2?domain=julien-brionne.fr&token=xxxxx gives me nothing but : 
https://webmention.io/api/mentions.jf2?token=xxxxx is answering with all my webmentions ? 

Thanks in advance !

**Comment by aaronpk** [comment]
Are your webmentions being sent to www.julien-brionne.fr instead?

**Comment by Akashrine** [comment]
No even https://webmention.io/api/mentions.jf2?domain=www.julien-brionne.fr&token=xxxxxx is not providing me anything.

**Comment by clottman** [comment]
I'm having the same issue.

**Comment by aaronpk** [comment]
Sorry for this long-standing bug. I fixed this in e1ae3d87ad492f0ee6e795d28f7a92e8448c2ae3 and it's live now.
