### ISSUE TITLE
There are no Webmentions yet! / potentially two accounts for one domain

### ISSUE THREAD

**Issue by M0nica** [aaronpk/webmention.io#169]
Thank you for creating this service!

 I am running into an issue where when I log into webmention.io now it says that I don't have any webmentions with the "There are no Webmentions yet!" message and if I use any of the API request links (with the associated user's token) that are visible when I am logged in there are no results returned. Also, the oldest webmention that is visible when I fetch all mentions without a limit or since param is from April 12th. I am not sure if that is expected or all related to this issue. 

## Potential Causes:

I think maybe I have a duplicate account for the **domain: aboutmonica.com** that I am unable to log into.
I am not sure if changing my Twitter handle caused some confusion with webmention.io although I believe I have logged in and seen incoming webmentions since renaming my handle. 

## Working Token for aboutmonica.com different than then token associated with my logged in user 

I have an old token in my env to fetch the webmentions. The request URL I am constructing is the same as the new one aside from the token and it returns results. However, I am not able to log in to webmention.io and see the particular token that is successfully fetching the data, instead I am seeing a different token which _should_ be associated with the same domain but is not returning results. 

When I log into webmention.io without aboutmonica.com and use the token visible when I log in the results for https://webmention.io/api/mentions.jf2?domain=aboutmonica.com&token=TOKEN&per-page=1 are: 
```{
  "type": "feed",
  "name": "Webmentions",
  "children": [

  ]
}
```

If I use the token that is not associated with the account that I am actively logged into then I get back: 

```{
  "type": "feed",
  "name": "Webmentions",
  "children": [
    {
      "type": "entry",
      "author": {
        "type": "card",
        "name": "Alley",
        "photo": "https://webmention.io/avatar/pbs.twimg.com/b499bc35df732473bd712fccd93ca5506f5e3ea31aef17632ea1e8dd62b7182c.jpg",
        "url": "https://twitter.com/alleyco"
      },
      "url": "https://twitter.com/alleyco/status/1385258671408615426",
      "published": "2021-04-22T15:46:18+00:00",
      "wm-received": "2021-04-22T22:22:10Z",
      "wm-id": 1130115,
      "wm-source": "https://brid.gy/post/twitter/indigitalcolor/1385258671408615426",
      "wm-target": "https://aboutmonica.com/blog/getting-started-with-webmention-next-js/",
      "content": {
        "html": "Webmentions let you pull tweets, other blogs, and activity from around the web into your site. <a href=\"https://twitter.com/indigitalcolor\">@indigitalcolor</a> explains how to add this functionality to a NextJS website. <a href=\"https://aboutmonica.com/blog/getting-started-with-webmention-next-js\">aboutmonica.com/blog/getting-s…</a>\n<a class=\"u-mention\" href=\"https://aboutmonica.com/blog/getting-started-with-webmention-next-js/\"></a>",
        "text": "Webmentions let you pull tweets, other blogs, and activity from around the web into your site. @indigitalcolor explains how to add this functionality to a NextJS website. aboutmonica.com/blog/getting-s…"
      },
      "mention-of": "https://aboutmonica.com/blog/getting-started-with-webmention-next-js/",
      "wm-property": "mention-of",
      "wm-private": false
    }
  ]
}
```

I hesitate to post the working read-only token here as I currently cannot log into an account to manage it if needed.

**Comment by aaronpk** [comment]
Hi! I do see a duplicate account. It looks like when you first logged in in April 2020 it was with `www.aboutmonica.com`, and this time it's `aboutmonica.com`. All the webmentions are stored on the one with the www subdomain. I just changed things around internally so when you log in you should see everything there again!

**Comment by M0nica** [comment]
Thank you for merging this data for me 🙌🏾 🎉.  I’m going to close this issue as I am now able to retrieve my historical webmentions when I make a request for all webmentions without a domain name ((https://github.com/aaronpk/webmention.io#find-all-links-to-all-sites-in-your-account ). When I pass in domain name param it seems I need to make two requests instead of one to receive the same info but I’m glad the API supports fetching data for multiple “sites” in lieu of the domain name param.
