### ISSUE TITLE
Unexpected no_link_found

### ISSUE THREAD

**Issue by kevincox** [aaronpk/webmention.io#170]
See https://webmention.io/kevincox.ca/webmention/psuT7wzaXh60I-vlpKAB

```json
{
  "status": "no_link_found",
  "source": "https://news.ycombinator.com/item?id=27402392",
  "target": "https://kevincox.ca/2021/06/04/http-range-caching/",
  "summary": "The Microformats at the source URL do not contain a link to the target URL. Check the source URL in a Microformats parser such as php.microformats.io"
}
```

https://php.microformats.io/?url=https%3A%2F%2Fnews.ycombinator.com%2Fitem%3Fid%3D27402392

```jsonc
{
   // ...
    "rel-urls": {
        // ...
        "https://kevincox.ca/2021/06/04/http-range-caching/": {
            "text": "The Impossibility of Perfectly Caching HTTP Range Requests",
            "rels": [
                "nofollow"
            ]
        }
    },
    // ...
}
```

The only reason I can see that it wouldn't work is that it is `rel=nofollow` however nether the webmetnion specs or any docs that I can find on webmention.io suggest that nofollow will prevent a webmention from verifying. Is this expected or is something funny happening?

**Comment by aaronpk** [comment]
Turns out this was because the XRay parsed result of the hackernews page didn't add the URL of the site linked to! I fixed that in XRay and it should be deployed now.
