### ISSUE TITLE
Added webmentions but I'm receiving none

### ISSUE THREAD

**Issue by iridant** [aaronpk/webmention.io#173]
I signed up with the indieAuth process, and added my twitter to brid.gy and it's not getting webmentions on my api page.  I'm tweeting and they're showing up on bridgy and I also inserted the pingback and webmention link tags on my page.  What's the issue?

**Comment by aaronpk** [comment]
@xrd whats your website? I'm curious how you ended up with "undefined" in the url of the webmention endpoint

**Comment by xrd** [comment]
@aaronpk Yes, I fixed this so it now displays `<link rel="webmention" href="https://webmention.io/svekyll.com/webmention">`.

So, I think I have the correct link in the page.

You can see it here at the bottom of the page in the source:

https://svekyll.com/Webmentions/

I made a tweet about it, was assuming that this would get a pingback (but I'm still trying to figure out if my mental model fits how this all works).

https://twitter.com/xrd/status/1443840765726060544

Thank you for the response!

**Comment by aaronpk** [comment]
In order to get responses from Twitter you'll also need to set up Bridgy, have you done that yet? https://brid.gy/

**Comment by xrd** [comment]
I had not. I just did. Is there a readme for brid.gy? I'm unsure if I have configured things correctly for my site (svekyll.com) or if I need to add it to the list of URLs in my twitter bio? Should I automatically get that tweet syndicated?

**Comment by aaronpk** [comment]
There's lots of info on the "help" page here https://brid.gy/about and also some more info on the indieweb wiki: https://indieweb.org/Bridgy

It should walk you through what you need to do to get it set up once you've connected your Twitter account.

**Comment by xrd** [comment]
Great. I'll read some more, thank you.

**Comment by snarfed** [comment]
We think https://github.com/aaronpk/XRay/pull/120 may have fixed this. Feel free to retry!
