### ISSUE TITLE
Bridgy webmentions not working

### ISSUE THREAD

**Issue by drivet** [aaronpk/webmention.io#175]
Hello,

I deleted the following webmentions from my dashboard:

https://brid.gy/like/twitter/desmondrivet/1392307647181950976/19779326
https://brid.gy/like/twitter/desmondrivet/1392307647181950976/171086225

After deleting those webmentions, I'm finding that:

- I can't resend the webmentions.  They don't appear again after I try.
- I can no longer receive any bridgy webmentions on webmention.io.  

For example, I manually sent a webmention, using Postman, to the following URL:

https://webmention.io/desmondrivet.com/webmention

using the following parameters:

Source: https://brid-gy.appspot.com/like/twitter/desmondrivet/1343693471828357129/3307359865
Target: https://desmondrivet.com/2020/12/28/175831

The post returned a 201 Created, and the Location returned in the response was:
https://webmention.io/desmondrivet.com/webmention/YEyXGKhXlHU4uEfS824G

Nothing shows up in the webmention.io dashboard for that webmention.  The Location above resolves to a page that says no link found, but I'm able to get the location in Postman fine, and it has my target URL in it.

Any idea what's up?  I thought it may have something to do with my imprudent deletion of those couple of bridgy webmentions at the start but I'm not sure.

Thank you and any help is appreciated!

**Comment by drivet** [comment]
Update: I read this issue:

https://github.com/aaronpk/webmention.io/issues/147

And I now realize that clilcking the X will delete and block the webmention from reappearing.  So now my question has changed: Is there a way to unblock webmentions?

I'm still not sure why subsequent bridgy webmentions don't appear...

**Comment by drivet** [comment]
Update:

While this source URL does not work:

https://brid-gy.appspot.com/like/twitter/desmondrivet/1343693471828357129/3307359865

this one does:

https://brid.gy/like/twitter/desmondrivet/1343693471828357129/3307359865

The first one is a redirect, the second one is the link it redirected to.

**Comment by snarfed** [comment]
We think https://github.com/aaronpk/XRay/pull/120 probably fixed this. Feel free to retry!
