### ISSUE TITLE
Webmentions are not received

### ISSUE THREAD

**Issue by xplosionmind** [aaronpk/webmention.io#178]
I am using [jekyll-webmention_io plugin](https://github.com/aarongustafson/jekyll-webmention_io) on my website to implement Webmentions. In some entries [on my website](https://github.com/xplosionmind/tommi.space 'tommi.space on GitHub'), Webmentions are not received, and after opening [this issue](https://github.com/aarongustafson/jekyll-webmention_io/issues/162) on the plugin repository, @fancypantalons [suggested](https://github.com/aarongustafson/jekyll-webmention_io/issues/162#issuecomment-1019382234) that it might be a webmention.io bug.  
I understand little of nothing about them, so I cannot really understand what is not working. I am available if you need any further information

**Comment by aaronpk** [comment]
Sounds like this was solved by making sure the webmentions are sent after the site is deployed

https://github.com/aarongustafson/jekyll-webmention_io/issues/162#issuecomment-1019431873
