### ISSUE TITLE
Webmention API not fetching any data 

### ISSUE THREAD

**Issue by logicman** [aaronpk/webmention.io#179]
Hello,
I just setup webmentions and signed up for Bridgy as well. I can see my tweet likes on the Webmention dashboard. That means its working. 

However, when I run this API, it gives me empty children.

`https://webmention.io/api/mentions.jf2?domain=sahilparikh.com&token=XXX`

```
{
  "type": "feed",
  "name": "Webmentions",
  "children": []
}
```

Any idea what I am doing wrong? Thanks.

**Comment by logicman** [comment]
This works if I remove the domain param in the GET call...

https://webmention.io/api/mentions.jf2?token=XXX

Is that ok?

**Comment by aaronpk** [comment]
Do the webmentions returned match the domain you are expecting?

Probably the most common reason for this is you end up logged in as a different domain, such as with a www prefix, which is seen as a totally different user.
