### ISSUE TITLE
Vouch parameter preventing processing?

### ISSUE THREAD

**Issue by gRegorLove** [aaronpk/webmention.io#185]
I've noticed this a few times with different sites using webmention.io: 

My automatic Webmention sending includes a vouch parameter and I get an HTTP 303 response with "Status: Pending" body, but it never seems to process. I'll use the URL `https://webmention.io/api/mentions.jf2?target=` to check if it's in the list of mentions for the target some time later and it isn't there. Then I'll usually use the form to manually re-send it (e.g. https://webmention.io/martymcgui.re/webmention) and it goes through within seconds.

This happened again about 15 minutes ago with [this post](https://gregorlove.com/2023/02/welcome-back/). 
A bit later I used the form on the [original post](https://francescoschwarz.com/notes/2023-02-13-16-25-33/) to submit and it showed up in seconds. The vouch parameter seems to be the only difference I can tell between the requests.

I don't have the webmention.io status URL for the automated WM, but the response body was HTML with:

```
Status: Pending
source	https://gregorlove.com/2023/02/welcome-back/
target	https://francescoschwarz.com/notes/2023-02-13-16-25-33
The webmention is currently being processed

Debug Info
{ "status": "pending", "source": "https://gregorlove.com/2023/02/welcome-back/", "target": "https://francescoschwarz.com/notes/2023-02-13-16-25-33", "private": false, "summary": "The webmention is currently being processed", "data": { } }
```

The status URL for the successful WM via Francesco's form:
https://webmention.io/francescoschwarz.com/webmention/XeopId-EWNC_jOQfLPNp

Edit: the automated webmention parameters from my site:
```
source=https%3A%2F%2Fgregorlove.com%2F2023%2F02%2Fwelcome-back%2F&target=https%3A%2F%2Ffrancescoschwarz.com%2Fnotes%2F2023-02-13-16-25-33&vouch=https%3A%2F%2Fgithub.com%2FgRegorLove
```

**Comment by aaronpk** [comment]
There is currently nothing in webmention.io that touches a `vouch` parameter, so I'm really not sure what to say here. Even when it calls out to XRay, it builds its own request so `vouch` is not part of that either.
