### ISSUE TITLE
11ty webmention fetch empty

### ISSUE THREAD

**Issue by kfitz** [aaronpk/webmention.io#188]
Hi! I'm using a lightly modified version of Max Böck's [eleventy-webmentions starter](https://github.com/maxboeck/eleventy-webmentions) on an 11ty site at [kfitz.info](https://kfitz.info/). I am building locally and then pushing the resulting site to my server. I definitely have webmentions in my dashboard that should be available for fetching, and nothing is throwing any errors, but no mentions are retrieved when I build. This is the key bit of the API request:

```
let url = `${API_ORIGIN}?domain=${domain}&token=${TOKEN}`
  if (since) {
	url += `&per-page=100&&since=${since}`
  } else {
	url += `&per-page=999`
  }

  const response = await fetch(url)
  if (response.ok) {
	const feed = await response.json()
	console.log(
	  `${feed.children.length} webmentions fetched from ${API_ORIGIN}`
	)
	return feed
  }
```

API_ORIGIN is set to `https://webmention.io/api/mentions.jf2`, my domain is set correctly, and my token is as well. Can you see anything in here that would prevent this call from producing results? Huge thanks for any help -- I've been bashing my head against this for days now.

**Comment by kfitz** [comment]
I am still trying to sort this webmentions issue out. The api url that’s supposed to pull all the mentions for this domain and then let them be processed by my script looks like this: 

`https://webmention.io/api/mentions.jf2?domain=kfitz.info&token=${TOKEN}`

However, when I run it it comes up empty. Zero. Nothing. However, a page-specific call like this contains all the mentions I'd expect:

`https://webmention.io/api/mentions.jf2?target=https://kfitz.info/eleventy/`

What am I missing?

**Comment by kfitz** [comment]
I've checked with snarfed at Bridgy and they suspect the issue is here: https://github.com/snarfed/bridgy/discussions/1512#discussioncomment-6428245

**Comment by snarfed** [comment]
We debugged a bit, and the webmentions themselves and the kfitz.info domain all seem ok. Possibly related: #161, #179

**Comment by snarfed** [comment]
We think https://github.com/aaronpk/XRay/pull/120 probably fixed this. Feel free to retry!

**Comment by kfitz** [comment]
Hmmm. Just running `npm run build` is still not fetching any webmentions, and `https://webmention.io/api/mentions.jf2?target=https://kfitz.info/` is still empty. Is there something I need to update locally in order for this to work? I super appreciate all the help!

**Comment by snarfed** [comment]
Oh, sorry, the fix here was just to webmention.io's processing of incoming webmentions from Bridgy specifically. If that was the problem here, try resending the Bridgy webmention(s), that might fix it.

**Comment by kfitz** [comment]
Ah, ok. I'm not sure that's the issue I was having. I posted this morning, and Bridgy captured these webmentions:

<img width="888" alt="Screenshot 2023-08-19 at 11 28 49 AM" src="https://github.com/aaronpk/webmention.io/assets/3170201/d8738cd3-3062-4d13-b21c-b163e8ab7de8">

Which appear in my webmention.io dashboard:

<img width="783" alt="Screenshot 2023-08-19 at 11 29 03 AM" src="https://github.com/aaronpk/webmention.io/assets/3170201/c3e73078-f6bd-4689-bfcd-faa1fdbd9128">

But which don't make it to [https://webmention.io/api/mentions.jf2?target=https://kfitz.info/](https://webmention.io/api/mentions.jf2?target=https://kfitz.info/), and so the Eleventy webmentions script can't grab them...

**Comment by kfitz** [comment]
One update: I edited `let url = '${API_ORIGIN}?domain=${domain}&token=${TOKEN}'` to `let url = '${API_ORIGIN}?token=${TOKEN}'` and that got Eleventy to retrieve webmentions! Now I just have to figure out what's preventing them from displaying. Thanks again for the help!

**Comment by aaronpk** [comment]
I was going to say, your previous comment shows you're using the `target` parameter which is for retrieving mentions of a specific page, not the entire site. 

`domain` should work to retrieve all mentions for the whole domain: https://github.com/aaronpk/webmention.io#find-all-links-to-your-domain

leaving out the `domain` and just using the `token` retrieves everything on your account regardless of the domain: https://github.com/aaronpk/webmention.io#find-all-links-to-all-sites-in-your-account

**Comment by kfitz** [comment]
Hmm interesting. Domain + token gives me an empty return, though token alone produces all mentions. Could there be a problem with ".info" being recognized as a tld?

**Comment by aaronpk** [comment]
I am trying to figure out why the combination of `domain` and `token` don't work for your account. It looks like there was a mixup with the webmention.io webmention endpoint on your account, and some of the webmentions went to a different account than you're using now. I'll see if I can fix the API to find those properly.

**Comment by kfitz** [comment]
Thank you!

**Comment by aaronpk** [comment]
Alright, that should be fixed now!

e1ae3d87ad492f0ee6e795d28f7a92e8448c2ae3

**Comment by kfitz** [comment]
Yay! That definitely returns mentions as expected now. In the process I uncovered several other configuration issues in my Eleventy setup, and I think there are a couple more to go, but it's starting to render now. I really appreciate all the help, and the amazing resource you're providing!

**Comment by aaronpk** [comment]
Glad to hear! Thanks!
