### ISSUE TITLE
Remove notification text generation

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/webmention.io#193]
This code is not well tested and has several bugs, and most people are not using the service in a way that requires this anyway.

This is the text like "X reposted a post that linked to Y" and "X commented 'bla bla' on a post"

**Comment by JoelOtter** [comment]
Hello! I think this has broken my use of Webmention.io and possibly that of others - as far as I can tell there's now no way to parse what type of interaction has been sent as a webmention? For example, I can't tell the difference between a like and a repost without parsing the source URL which may not work for stuff that doesn't come from a silo.

**Comment by JoelOtter** [comment]
FWIW here's the code I currently use to format stuff from webmention.io:

```js
  fetch("https://webmention.io/api/mentions?token={{ .Site.Params.webmentions.token }}&target=" + {{ .Permalink }}).then(
    response => response.json()
  ).then(jsonData => {
    let data = {};
    for (const link of jsonData.links) {
      if (!data[link.activity.type]) {
        data[link.activity.type] = [];
      }
      data[link.activity.type].push(link.data);
    }
    return data;
  }).then(data => {
    const interactionsDiv = document.getElementById('interactions');
    if (data['repost']) {
      createInteractionGroup(interactionsDiv, "reposts", data.repost, "fa-retweet");
    }

    if (data['like']) {
      createInteractionGroup(interactionsDiv, "likes", data.like, "fa-heart");
    }

    if (data['reply']) {
      createReplyGroup(interactionsDiv, data.reply);
    }
  });

```

**Comment by aaronpk** [comment]
It looks like you're using the older JSON API, try switching to the new one and there is a property `wm-property` which should tell you the same thing. This is the format listed on the docs now: https://webmention.io/#show-all-mentions

But since you're probably not the only one relying on this property, I added it back to the legacy JSON format too.

**Comment by JoelOtter** [comment]
Thank you! I’ll have a look at migrating on my end to the new API :)

**Comment by JoelOtter** [comment]
Thanks for this, I've now migrated over. As a tiny piece of feedback, the `published_ts` property is very useful for sorting on and is missing from the newer API.

**Comment by aaronpk** [comment]
Good tip, tracking that here: #199
