### ISSUE TITLE
Remove ghost webmention

### ISSUE THREAD

**Issue by reesericci** [aaronpk/webmention.io#207]
Hello - 

I have somehow managed to create a webmention that does not appear in my dashboard to remove, despite it being created on my own domain. The id of the webmention is `1826101`, and I would like for it to be deleted. It is on the URL `https://place.reeseric.ci/writings/2024-05-05/` and the source is `https://almond-tattered-license.glitch.me/`.

Thank you!

**Comment by aaronpk** [comment]
I see what happened. This is a side effect of some very old architectural decisions in webmention.io. It's deleted now.
