### ISSUE TITLE
FedCM is only called when version == 126, should be > 126

### ISSUE THREAD

**Issue by samuelgoto** [aaronpk/webmention.io#209]
In line:

https://github.com/aaronpk/webmention.io/blob/main/public/js/fedcm.js#L74

```javascript
if(navigator.credentials && getChromeVersion() == 126) {
  signIn();
}
```

We should use instead:

```javascript
if(navigator.credentials && getChromeVersion() >= 126) {
  signIn();
}
```

Chrome canaries are already in 127, so webmention.io stopped calling FedCM since yesterday's push.

**Comment by aaronpk** [comment]
🤦  I *thought* that's what I wrote. Fixed in df8684f382dee08901f68b4b400ee315fdbd9b33.
