### ISSUE TITLE
PKCE code verifier should be at least 43 characters

### ISSUE THREAD

**Issue by FenTiger** [aaronpk/webmention.io#213]
I am unable to log in to webmention.io with [my toy FedCM implementation](https://codeberg.org/FenTiger/FedIAM) because the OIDC library I am using fails with [this error](https://github.com/ory/fosite/blob/8631deb35b30a927970c216a58985ab17e6e471d/handler/pkce/handler.go#L175):
```
	// Validation
	if nv < 43 {
		return errorsx.WithStack(fosite.ErrInvalidGrant.
			WithHint("The PKCE code verifier must be at least 43 characters."))
```

From [RFC7636](https://datatracker.ietf.org/doc/html/rfc7636#section-4.1):
```
   code_verifier = high-entropy cryptographic random STRING [...] with a minimum length of 43 characters
```

But it looks like webmention.io is using [30 characters](https://github.com/aaronpk/webmention.io/blob/10391b2816a3436ff1c6e9ef16af73cc4376a4b9/controllers/auth.rb#L97):
```
  post '/auth/fedcm-start' do
    session[:code_verifier] = SecureRandom.urlsafe_base64 30
    base64_str = Digest::SHA256.base64digest(session[:code_verifier])
```

Should this be changed?

**Comment by aaronpk** [comment]
Good catch, thank you. Yes this should be fixed.
