### ISSUE TITLE
recent webmentions vs all webmentions

### ISSUE THREAD

**Issue by joejenett** [aaronpk/webmention.io#218]
When logged in at webmentions.io, I am able to view a list of "Recent Webmentions." That list shows mentions going back to 7/31/24. 

Does that mean that data prior to 7/31/24 is no longer in the database? 
Does webmention.io retain data for only the most recent webmentions? 

I also noticed the json file pertaining to the api token only has mentions going back to 9/2/24. Any mentions which occurred between 7/31/24 and 9/2/24 are no longer in the json file and therefore, no longer appear on the posts they pertained to.

I wouldn't mind recovering the older data nor hosting that data myself if necessary.

Thanks (the account in question is https://iwebthings.joejenett.com/)

**Comment by Ryuno-Ki** [comment]
I observed it as well with https://jaenis.ch/ (and moved on to host my own server for processing webmentions as a consequence).
