### ISSUE TITLE
If no trailing slash on a domain, add it before checking for a linkback

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/webmention.io#4]
When the source or target is something like `http://aaronparecki.com`, it should be treated as if it were actually `http://aaronparecki.com/`

**Comment by aaronpk** [comment]
Closing with no action required. If the target parameter has no trailing slash, then it already checks for that literal string in the source document. Sending a webmention with a target of http://example.com when the page contains the string `http://example.com/` is not valid anyway.

**Comment by binyamin** [comment]
@aaronpk Just ran into this issue, the other way around.  Target had a slash, but the source document did not. https://webmention.io/manuelmoreale.com/webmention/lskMvHhT259uRpeXAmZf

**Comment by aaronpk** [comment]
Which form were you using? This one?

https://webmention.io/manuelmoreale.com/webmention

You're expected to put the correct target URL in that form too. It's not straightforward to "normalize URLs" like you're talking about because of all the different ways they can differ.
