### ISSUE TITLE
Webmentionned in a reply to another link

### ISSUE THREAD

**Issue by eliemichel** [aaronpk/webmention.io#40]
When a post contains something like `<a class="in-reply-to">Foo</a> <a>Webmention.io</a>`, which means it is a reply to Foo, Webmention.io sees itself as the reply target if it is webmentioned.

For example, [this article](http://known.exppad.com/2015/des-nouvelles-de-freeder) contains a `in-reply-to` link toward http://slopjong.de/2012/03/31/curl-follow-locations-with-safe_mode-enabled-or-open_basedir-set/ and, in another sentences, mentions http://indiewebcamp.com/php-mf2. IndieWeb considers the post as a reply to http://indiewebcamp.com/php-mf2 although this is not the case.

It should say "Élie Michel posted a comment that linked to indiewebcamp.com" instead of "Élie Michel commented on https://indiewebcamp.com".

**Comment by aaronpk** [comment]
This feature has since been removed.
