### ISSUE TITLE
Invalid Input

### ISSUE THREAD

**Issue by bl4ckdu5t** [aaronpk/webmention.io#43]
When I visit <http://webmention.io/api/mentions?domain=http://josephrex.me> where I have the webmention and xmlrpc link, I get the following:
```
{"error":"invalid_input","error_description":"Either an access token or a target URI is required"}
```
Then when I visit <http://webmention.io/api/mentions?target=http://josephrex.me> I get:
```
{"links":[]}
```
I expect to see a link at least because the blog has some backlinks. If it doesn't work this way, how do I know when I get pingbacks?

**Comment by aaronpk** [comment]
@bl4ckdu5t You can sign in and get your API token, which is used with the domain parameter:

http://webmention.io/api/mentions.jf2?domain=josephrex.me&token=xxxx

You can also configure web hooks after signing in, to have webmention.io post the comment data to you whenever it's received.
