### ISSUE TITLE
Disappearing mentions

### ISSUE THREAD

**Issue by aarongustafson** [aaronpk/webmention.io#46]
I ran into an issue where mentions disappeared from the API. Specifically, [this mention from Google+](https://www.brid.gy/log?start_time=1427495790&key=aglzfmJyaWQtZ3lyWQsSCFJlc3BvbnNlIkt0YWc6cGx1cy5nb29nbGUuY29tLDIwMTM6ejEybHc1cnowb21wZ2RmZGIyMzVkdmR6ZHJ6dXozeG1iLjE0Mjc0ODk1MDc0NDkwMjkM) (and some others from Stuart) are no longer appearing when I [query webmention.io for the target URI](http://webmention.io/api/mentions?target=http://www.aaron-gustafson.com/notebook/playing-with-flexbox-and-quantity-queries/).

I do recall them being in the list at one point. Not sure what happened.

**Comment by aaronpk** [comment]
Did you try using the paging options? I wonder if they just fell off the first page of results?

**Comment by aarongustafson** [comment]
Hmm, I did not know there were paging options. Is that new? Off to check the API…

**Comment by aaronpk** [comment]
Nope it's been there a while, but it just occurred to me that we hadn't talked about that before. It's also only documented in the readme of this repo, not on the webmention.io site: https://github.com/aaronpk/webmention.io#paging

**Comment by aarongustafson** [comment]
Yup, I think that picked it up. No wonder I hadn’t seen the pagination stuff when I did my original implementation (November of 2014). The domain search is interesting too. It feels a little hacky, but I guess I can set an arbitrarily high `perPage` (9k or something). Would you be at all averse to a * value to grab everything? I don’t want to abuse the system, but I would like to fine ways to effectively cache webmentions in the static site context.

**Comment by aaronpk** [comment]
I'd say go for it and I'll deal with the backend if we need to. It's ultimately not that much data so it shouldn't be a problem!

**Comment by aarongustafson** [comment]
Thanks!
