### ISSUE TITLE
IndieAuth login misses the path part of provided account URL

### ISSUE THREAD

**Issue by elf-pavlik** [aaronpk/webmention.io#47]
I tried to log in with https://wwelves.org/perpetual-tripper just as I do for example at http://indiewebcamp.com/User:Wwelves.org_perpetual-tripper but it missed the */perpetual-tripper* part and just kept the domain part *wwelves.org*

```html
<link rel="pingback" href="https://webmention.io/wwelves.org/xmlrpc" />
<link rel="webmention" href="https://webmention.io/wwelves.org/webmention" />
```

![Webmention.io error](https://lh5.googleusercontent.com/ErypiO6NmTO3YjOOyskO8zC9ZKDm1EWNy13Ug88L-8_l3F3zoW11gZwrBH2z44fHNsQJ688STsyv_us=w1256-h573)

**Comment by aaronpk** [comment]
Webmention.io only supports root-domain IndieAuth IDs, since the domain name is used in the path to the webmention endpoint. I may try to solve this in the future by allowing users to customize what appears in the webmention endpoint URL, but this isn't a priority for now.
