### ISSUE TITLE
Add web hook to notify a site when a new webmention is processed

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/webmention.io#55]

**Comment by diplix** [comment]
+1

**Comment by aaronpk** [comment]
This is in place now, need to make a UI for configuring it which I'll do on a new issue.

**Comment by diplix** [comment]
started using the webhoo a couple of days ago. however, after some trying it out, found out that after the webhook gets pinged, i had to wait about 30 or 40 seconds (or a bit more) until the api returns the newly added mention. i didn’t poke around a lot, so there might be another problem, but from what i tried, it looks like i have to wait a little, to get the full API reply. 

i could of course use the payload, but that thought crossed my mind a little too late (while writing this issue).

**Comment by aaronpk** [comment]
hm that's odd, i'm surprised the delay is that long. I'll see what I can do to fix it, but I'm planning on using the data from the payload directly.
