### ISSUE TITLE
missing data from bridgy mentions

### ISSUE THREAD

**Issue by diplix** [aaronpk/webmention.io#56]
this twitter reply (and some other replys and likes)
https://twitter.com/Nevid/status/637019490241392640
https://brid-gy.appspot.com/comment/twitter/diplix/637001027972022272/637019490241392640

produce mentions with missing data at webmention.io
http://webmention.io/api/mentions?perPage=200&page=0&target[]=http://wirres.net/article/articleview/8434/1/6/
```
{"source":"https://brid-gy.appspot.com/comment/twitter/diplix/637001027972022272/637019490241392640","verified":true,"verified_date":"2015-08-27T21:51:38+00:00","id":92696,"data":{"url":null,"author":{"name":"David Prochnow","url":"http://www.davidp.de/","photo":"https://twitter.com/Nevid/profile_image?size=original"},"name":null,"content":null,"published":null,"published_ts":null},"activity":{"type":null,"sentence":null,"sentence_html":null},"target":"http://wirres.net/article/articleview/8434/1/6/"}
```
→ note that data:url and activity:type are is missing/null, although bridgy provides all necessary data.

this seems to be happening only since yesterday evening (CET), starting about 10 to 12 hours from now.

sending the mention again, does not seem to update the webmention.io data
```
curl -i -d "source=https://brid-gy.appspot.com/comment/twitter/diplix/637001027972022272/637019490241392640&target=http://wirres.net/article/articleview/8434/1/6/" https://webmention.io/wirres.net/webmention
```
http://webmention.io/api/mentions?perPage=200&page=0&target[]=http://wirres.net/article/articleview/8434/1/6/

**Comment by diplix** [comment]
seems to work again. may be the last commit fixed it or there was a hickup somewhere.

**Comment by aaronpk** [comment]
Thanks, yeah I fixed it in the last update.
