### ISSUE TITLE
Add option to send web hook in Trackback format

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/webmention.io#62]
to support blogs that can receive Trackbacks.

Please chime in if this is something you'd be interested in seeing!

**Comment by onli** [comment]
I'd be interested in this. 

https://github.com/s9y/Serendipity supports pingbacks and trackbacks, and the trackbacks are too similar for me to consider adding webmentions. But if this service would convert webmentions to trackbacks, I will propose to the other team members to add into our themes a webmention-header pointing to the converter url of webmention.io. This way, modern serendipity blogs could receive webmentions as trackbacks.

**Comment by aaronpk** [comment]
This hasn't gotten enough interest to justify the effort. Closing without plans to add this option.
