### ISSUE TITLE
Create API to retrieve RSVPs

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/webmention.io#64]
should render a facepile or list of RSVPs for a URL, so that they can be embedded in event pages

**Comment by tantek** [comment]
I totally need this now :) - also it seems webmention.io is not parsing for p-rsvp at all, e.g. this RSVP has rsvp:no:
http://pin13.net/mf2/?url=https%3A%2F%2Fdougbeal.com%2F2017%2F06%2F25%2Fhomebrew-website-club-at-mozilla-sf-tantek%2F

but does not show up in webmention.io's mentions: 
https://webmention.io/api/links.jf2?target=http://tantek.com/2017/179/e1/homebrew-website-club

**Comment by tantek** [comment]
Note webmention.io appears to also be missing these responses:
* https://werd.io/2017/no-unfortunately-i-cant-go-this-time
* http://known.kevinmarks.com/2017/no-ill-be-in-yorkshire
(both posted with Known)

**Comment by sknebel** [comment]
@tantek: webmention.io handles rsvp properties, but there are some bugs, especially with outputting them to JF2, in the JSON version they appear better. See #80, #81

**Comment by tantek** [comment]
@sknebel fixing #80 and #81 are higher priority than this feature request IMO.

Similarly, I think #84 is both higher priority and less work.

Lastly, after 80, 81, 84 are resolved, consider that #83 may be better (more general while similar work, solves more use-cases) or perhaps a nice step towards this RSVP specific API for embedding (which could undoubtedly just use the #83 feature to get RSVP specific data first before formatting it for embedding). Just trying to help by breaking the problem down into smaller problems :)

**Comment by aaronpk** [comment]
This can be accomplished with the new `wm-property=rsvp` filter added for #83. See docs in the readme: https://github.com/aaronpk/webmention.io#find-links-of-a-specific-type-to-a-specific-page
