### ISSUE TITLE
Incorrect encoding for data.author.name in https://webmention.io/api/mentions output

### ISSUE THREAD

**Issue by dogada** [aaronpk/webmention.io#65]
Since today Cyrillic text in `data.author.name` of https://webmention.io/api/mentions  returned in non-readable form. Yesterday same mention returned properly encoded. Only `data.author.name` is affected, rest of Cyrillic fields are ok.

Please take a look at following webmention:
 ```js
{ source: 'https://brid-gy.appspot.com/post/twitter/d0gada/696583747706064900',
  verified: true,
  verified_date: '2016-02-09T13:12:09+00:00',
  id: 221539,
  data:
   { author:
      { name: '??? ?????? ???????'}
   }
}
```

**Comment by aaronpk** [comment]
@dogada can you check again? Yesterday I was making some changes to how things are handled to better support Emoji characters. It looks like I slightly overcorrected for that and introduced this new problem. :-) It looks like it's fixed now at least for some of the issues I was seeing.

**Comment by dogada** [comment]
@aaronpk works again, thanks for the quick fix.
