### ISSUE TITLE
webmention.io seems to miss lots of webmentions

### ISSUE THREAD

**Issue by diplix** [aaronpk/webmention.io#66]
webmention.io accepts webmentions from brid.gy, but i think that not all of them are processed — or if they are processed, are not returned via the API.
one or two examples, that were resend a couple of times through bridgy and at least once through telegraph, but don’t show up in the [api response](http://webmention.io/api/mentions?target=http%3A%2F%2Fwirres.net%2Farticle%2Farticleview%2F9340%2F1%2F6%2F&submit=get):
* https://telegraph.p3k.io/webmention/10W2mC0c5bkksn1OcW/details
* https://telegraph.p3k.io/webmention/10rJ0xxypxIhYGivK7/details

there are other mentions that show up, but processing takes a rather long time (up to 3-6 minutes). my guess is either high server load or some problem with the queue, that might drop mentions. i’d be glad if you had a look into that, since i suspect that i’m not the only user experiencing this.

**Comment by diplix** [comment]
just received https://telegraph.p3k.io/webmention/10W2mC0c5bkksn1OcW/details — about 20 minutes after resending it twice.

**Comment by aaronpk** [comment]
wow that's really strange. I was actually just testing it myself, so that may have been me. It's also getting a lot of traffic right now from what looks like someone's script that has gone a little rogue, so it could be that everything is just delayed too.

**Comment by diplix** [comment]
yeah, thats what i was suspecting, serverload or a rougue script or script-kid.

**Comment by diplix** [comment]
if you’re confident that no mentions are dropped, only delayed, go ahead an close this issue. (some mentions drop in more with than 24 hours delay, but i’m not sure wheter thats bridgy or webmention.io). /me working on my patience.

**Comment by aaronpk** [comment]
I'm not confident at all, so feel free to keep watching.

Part of the things you could be seeing is that bridgy will sometimes stop paying attention to older tweets. I think they have to be quite a bit older than 24 hours though. If you see that Telegraph sent something, but it's not showing up in webmention.io, then that's definitely a webmention.io problem.

**Comment by diplix** [comment]
mentions seem to be dripping in now, one after the other.

**Comment by aaronpk** [comment]
That's good to hear! I'm still getting hammered by the same webmention loop but glad things are still chugging along.

**Comment by aaronpk** [comment]
I just hard-coded a check to drop those mentions I was getting hit with, but I am worried that it may have dropped the entire queue.

**Comment by diplix** [comment]
no problem. i’ll retrigger.

**Comment by diplix** [comment]
looks like everything works again. still takes a while, but not nearly as long as in the last 2 days.
