### ISSUE TITLE
Received webmention with empty author for a page with p-author MF2 

### ISSUE THREAD

**Issue by dogada** [aaronpk/webmention.io#71]
I got a webmention from source page https://petermolnar.eu/o37tvb/ (web-site of @petermolnar)  that has `p-author` mf2 but received webmention have empty author field. 

Not sure where is the root of problem, probably smth wrong with mf2 usage on a page.

```html		
by <span class="p-author h-card vcard">
  <a class="fn p-name url u-url" href="https://petermolnar.eu/about">Peter Molnar</a>
</span>
```

```js
{ 
  source: 'https://petermolnar.eu/o37tvb/',
  target: 'https://dogada.org/e/118ZupYo13916',
  post:
   { type: 'entry',
     author: { name: null, photo: null, url: null },
     url: 'https://petermolnar.eu/o37tvb/',
     published: '2016-02-27T16:59:35+00:00',
     name: '',
     content:
      { 'content-type': 'text/html',
        value: ' \n\t\t\t\t<p><strong>RE:</strong> <a href="https://dogada.org/e/118ZupYo13916" rel="nofollow">dogada.org/e/118ZupYo1391
6</a></p>\n<blockquote>\n<p>Peter, <a href="https://www.subtome.com" rel="nofollow">https://www.subtome.com</a> AFAIK just redirects you
 to a RSS/Atom reader and such buttons exist for ages. </p>\n</blockquote>\n<p>There’s a little more to that. subtome could include h-fe
ed parsers as options as well.</p>\n<blockquote>\n<p>RSS is dying and I prefer #IndieWeb h-feed because it’s part of web-site instead of
 an invisible XML-addition.<br>\nRSS is dying for an simple reason — it’s one-directional publisher-&gt;subscriber technology. With rise
 of social networks with their #P2P communications RSS is really "walking dead" if we talk about human-to-human communications. RSS stil
l used for one-directional <em>public</em> updates (news, announcements, etc) distribution.</p>\n</blockquote>\n<p>Valid reasoning, and 
I’m not going to deny the truth of it. However, for me, a reacji is not interaction – which is currently rising on the silos – so while 
the option of interaction is important, the content of these reactions are becoming less and less relevant and significant.</p>\n<blockq
uote>\n<p>The ‘Subscribe’ button I miss should allow to subscribe to an private h-feed (like family or company feed) and allow bidirecti
onal communication: I should be able to send comments to feed’s owner and receive replies back.</p>\n</blockquote>\n<p>I totally agree t
hat we need a solution for the missing Follow/Subscribe option. However, I think this is more of a missing service/infrastructure than a
n actual missing #indieweb feature.</p>\n<p>Similarly to this, <a href="/how-i-misunderstood-an-aspect-of-indieweb/" rel="nofollow">my g
reatest itch is content discovery</a> as I’m dealing with RSS &amp; Mf2 by sending them as mail from a list of URLs as subscribed for si
tes. To think of it, it may not be impossible to add a little glue system that handles reply email for those posts sent as one and let m
y site post them as actual replies…</p>\n<p>You’ve just given me an idea, thank you!</p>\n\t\t\t ' },
     'in-reply-to': 'https://dogada.org/e/118ZupYo13916',
     'wm-property': 'in-reply-to' } }
```

The webmention also misses name, but the source page has empty `h-entry p-name` as well. Probably it may sense to generate webmention entry name from e-content in this case?

**Comment by aaronpk** [comment]
I saw this yesterday, and mentioned it to Peter. He previously did not have an author h-card on the page for replies, but added it yesterday after I pointed it out. 

I'm not sure what you mean about the p-name property. I see an empty p-name span in his source: `<span class="p-name"></span>`

**Comment by petermolnar** [comment]
@dogada I had an empty p-name on notes, as they don't have titles; I've changed that to be the same as the e-content according to http://microformats.org/wiki/h-entry#p-name_of_a_note

As for the h-card, I had that site-wide instead of on per h-entry; also fixed. Can you try parsing it again, please?

**Comment by aaronpk** [comment]
Personally I think a blank p-name for notes is fine. When consuming the parsed version with a non-blank name, I have to compare it to the content to check if it's distinct, and then I toss out the name after I determine it's a note. Having the name be blank saves me a step anyway.

**Comment by dogada** [comment]
I agree that blank p-name is ok from for short (several sentences) notes I have only e-content as well. However from webmention receiver point of view much better to have text-only webmention name that I can show on my web-site. If I don't have p-name, I need to sanitize html received in entry.post.content and this is much harder.

Anyway for me isn't clear how to preserve formatting during webmentions exchange. If source is just one paragraph of text all is simple. But what to do if source is big article with complex html? In this case  I think source author SHOULD provide text only p-name (one sentence) or p-summary (one paragraph).

**Comment by aaronpk** [comment]
p-summary is ideal, especially if it's hand-crafted by the author.

If you ever get HTML content in the content property, the parser also provides a plaintext version of it though. That's why you always see parsed results like:

```
{
  "content": {
    "html": "<b>Hello World</b>",
    "value": "Hello World"
  }
}
```

I agree that deciding how to actually display a comment can be tricky. I would definitely recommend reading this thoroughly: http://indiewebcamp.com/comments-presentation#How_to_display There's a lot of good thoughts there, and that's how I currently display comments on my site.

I've also been working on a lot of changes for how webmention.io parses content from a page, so expect to see some big changes on that front soon. (It will of course be backwards compatible if any of the actual data structure changes, but I'm hoping to avoid requiring consumers of webmention.io to need to change anything). See #70 and the work on [XRay](https://github.com/aaronpk/Xray) for more details.

**Comment by dogada** [comment]
> As for the h-card, I had that site-wide instead of on per h-entry; also fixed. Can you try parsing it again, please?

@petermolnar Actually parsing is done by webmebtion.io, I receive already parsed webmention via web hook. You can send me an webmention and I will show what I get.

@aaronpk BTW, other confusing thing from webmention receiver point of view: web hook and  http://webmention.io/api/mentions endpoint returns webmentions in different formats, so it's a bit tricky to parse them with same code.

**Comment by aaronpk** [comment]
@dogada Try http://webmention.io/api/mentions.jf2 and you should get the data from the API in the same format as the web hook.

**Comment by dogada** [comment]
@aaronpk thanks for the hint, will try http://webmention.io/api/mentions.jf2 tomorrow.

**Comment by aaronpk** [comment]
I'm going to close this as the original issue has been addressed. Feel free to open a new issue if you see any issues with the API vs webhook formats.
