### ISSUE TITLE
empty webmention from bridgy/facebook comment

### ISSUE THREAD

**Issue by diplix** [aaronpk/webmention.io#72]
i get `"content":null` from this webmention.io query (id 311629):
http://webmention.io/api/mentions?target=http%3A%2F%2Fwirres.net%2Farticle%2Farticleview%2F9470%2F1%2F6%2F&submit=get

the bridgy proxy page and what xray is parsing are quite OK:
https://brid-gy.appspot.com/comment/facebook/548616784/10153579325441785/10153579325441785_10153579676866785

https://xray.p3k.io/parse?url=https%3A%2F%2Fbrid-gy.appspot.com%2Fcomment%2Ffacebook%2F548616784%2F10153579325441785%2F10153579325441785_10153579676866785

bridgy log: https://brid.gy/log?start_time=1457092581&key=aglzfmJyaWQtZ3lyRwsSCFJlc3BvbnNlIjl0YWc6ZmFjZWJvb2suY29tLDIwMTM6MTAxNTM1NzkzMjU0NDE3ODVfMTAxNTM1Nzk2NzY4NjY3ODUM

i resubmitted the bridgy post to webmention.io once already, but webmention.io still returns an empty content on that entry. maybe some encoding issue?

btw.: the webmention.io status page is fine, too: https://webmention.io/wirres.net/webmention/XNAT-qufrFd2btsHIyk1

**Comment by aaronpk** [comment]
ah thanks! Looks like I forgot to update the `api/mentions` path to pull the plaintext content. (I recently switched to storing plaintext and html content separately.)

**Comment by diplix** [comment]
thanks!

**Comment by diplix** [comment]
(side effect of this flaw was, btw, that the content field contained the original html from bridgy, including the <img> markup, if present. thats gone now — no more html. i’m wondering: is that intentional, that webmention.io does not pass the html, only plain text?

**Comment by aaronpk** [comment]
Good catch. I switched it to prioritize the HTML content if it's there.

Webmention.io now sanitizes the HTML pretty heavily, thanks to XRay. A small subset of "safe" HTML tags are allowed, and all attributes except mf2 classes are removed from elements as well. The goal is to have the HTML returned by this API always be safe to render as a comment as is, without you needing to sanitize it further.

**Comment by diplix** [comment]
good. now everything is great again :)
her’s a webmention showing an image: http://wirres.net/article/articleview/9470/1/6/#trackback311556
