### ISSUE TITLE
Web hook config form isn't shown in Dashboard

### ISSUE THREAD

**Issue by dogada** [aaronpk/webmention.io#74]
Just signed in on webmention.io with https://memolot.com and didn't see web hook config section on the Dashboard page (https://webmention.io/dashboard). I can see API key but Webhook form isn't shown at all.

I suppose it's because `user.sites` isn't initialized properly for some reason and hence following loop output nothing: 
https://github.com/aaronpk/webmention.io/blob/87ed251a0775269941c4e42763fbabc2b5dbf162/views/dashboard.erb#L31

**Comment by aaronpk** [comment]
There is no "create" step for sites, they are created as soon as the first webmention for the domain is received. Can you send yourself a webmention to that domain and then check if it shows up on the dashboard?

**Comment by dogada** [comment]
Thanks. Sent first webmention and form is showed now.
