### ISSUE TITLE
rename the project?

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/webmention.io#78]
this should not be named the same thing as the Webmention specification

**Comment by cweiske** [comment]
Related to https://github.com/aaronpk/IndieAuth.com/issues/138

**Comment by aaronpk** [comment]
I'm on the fence about whether it's necessary to rename this actually.

Unlike IndieAuth, I don't think people are confused about whether the Webmention spec is tied to webmention.io.

Also, .io is already commonly used for services for things, so it's not as confusing as if this were at `webmention.com` for example.

**Comment by aaronpk** [comment]
If you use webmention.io, it's because you've found it and signed up for it. That's different from indieauth.com which you might see if you're signing in to a totally unrelated website. (e.g. the indieweb.org wiki)

**Comment by aaronpk** [comment]
Six months later, and I'm still not convinced this is actually a problem. Maybe it's because Webmention has enough gravity on its own. I don't see people being confused about whether webmention.io is somehow centralizing the Webmention spec, which is what was happening with indieauth.com.

**Comment by swentel** [comment]
As a fairly new consumer of indieweb, the confusion with webmention.io is much less then with indieauth(.com), so yeah, I think it's totally fine to keep it like this :)

**Comment by aaronpk** [comment]
I've been thinking about this for a while now and I don't think I will rename this after all. It doesn't seem to be causing confusion. If anything, I will eventually launch a new service with a better name.
