### ISSUE TITLE
inconsistent handling of upper/lowercase in RSVP processing

### ISSUE THREAD

**Issue by sknebel** [aaronpk/webmention.io#81]
When an RSVP post is processed, the `rsvp` value as it appears in the post is taken from the source post (via XRay) and used to create the post type 
([/helpers/webmention_processor.rb#L297](https://github.com/aaronpk/webmention.io/blob/d9bd7967431277ae1b9eaca6445a9330ed2ae592/helpers/webmention_processor.rb#L297)):
```ruby
    if rsvp = entry['rsvp']
      phrase = "RSVPed #{rsvp} to"
      link.type = "rsvp-#{rsvp}"
```

When generating the JSON output, this value is passed through as is ([/helpers/formats.rb#L41](https://github.com/aaronpk/webmention.io/blob/d9bd7967431277ae1b9eaca6445a9330ed2ae592/helpers/formats.rb#L41)):

```ruby
      obj[:activity] = {
        :type => link.type,
        :sentence => link.sentence,
        :sentence_html => link.sentence_html
}
```
When generating the JF2 output, a specific list of cases is matched ([/helpers/formats.rb#L136](https://github.com/aaronpk/webmention.io/blob/d9bd7967431277ae1b9eaca6445a9330ed2ae592/helpers/formats.rb#L136)):
```ruby
when "rsvp-yes"
    relation = :"rsvp"
    jf2[:rsvp] = "yes"
```

I believe this explains some of what @tantek has been commenting on over in #64. From https://indieweb.org/rsvp it is not immediately clear to me if rsvp values are supposed to be case-sensitive or not? (@tantek again)

**Comment by tantek** [comment]
Per http://microformats.org/wiki/h-entry which defines p-rsvp, yes, rsvp values must be parsed case-insensitive.

**Comment by aaronpk** [comment]
I just pushed a fix to XRay that will convert RSVP values to lowercase, which will help this problem going forward. I also pushed a fix to webmention.io in bfdd4e6e51c80fc6434a8018e87f08368e3e4c3e to convert to lowercase.
