### ISSUE TITLE
Feature request: aggregate webmentions for a link (# of rsvps of each type, # comments / reposts / likes)

### ISSUE THREAD

**Issue by tantek** [aaronpk/webmention.io#82]
Feature request: would be nice to have a jf2 endpoint that takes a URL (for which webmention.io receives/tracks webmentions) and returns aggregate webmentions for a link, e.g. 
* number of rsvps of each type, 
* number of likes
* number of reposts
* number of comments etc.

Some real-world use-cases (that would result by post-processing this jf2 by some theoretical jf2->html converter)
1. "4 comments, 2 reposts, 23 likes" (e.g. as seen in icon representation in footer of this tweet permalink https://twitter.com/rachelandrew/status/882224351688482816 ). Thus 4, 2, 23 in properties for # of comments, reposts, likes.
2. "7 Went · 1 Interested" - simple aggregation of RSVP values. Thus 7,0,1,0 in properties for yes,maybe,interested,no. (from https://www.facebook.com/events/1935019616733708/) Could likely be same aggregate endpoint as the one that returns 1. above.
3. "Aaron, Ben, and 3 others went" - summary of N (parameterized n?) aggregation of a specific RSVP value. Similar to current links.jf2 result except showing only first N responses of that type e.g. rsvp:yes - also parameterized in request URL. (ibid)

**Comment by tantek** [comment]
(Aside: consider this lower priority than #80 #81 #83 )

**Comment by aaronpk** [comment]
I'm not quite sure how this is related to jf2, but there is already an API for returning the total number of webmentions for a given link. I'm expanding this to group them by type as well.

**Comment by aaronpk** [comment]
Done in 689de047356cd331ba69cb5aa05132be196a5982
