### ISSUE TITLE
Feature: persistent webmention delete

### ISSUE THREAD

**Issue by tantek** [aaronpk/webmention.io#86]
Since webmention.io collects received webmentions, there needs to be a way (authenticated API or UI) to persistently delete a received webmention. That is:

* notify webmention.io (via UI or API) that a particular received webmention should be deleted from webmention.io's collection (that is, no longer returned in any API calls etc.)
* if webmention.io receives another webmention with that same 'source', it should reject it (hence the "persistent delete"

This is essential for removing specific abusive webmentions (whether comments, or likes/reposts by abusive accounts).

**Comment by tantek** [comment]
Note that this is NOT a request for block lists (other issues cover that which is a lot more work), this is specifically just for *some way* to delete specific webmention permalinks so they stop showing up in API calls.

**Comment by tantek** [comment]
brainstorm possible "minimal" UI:
* IndieAuth login
* form field to enter a webmention source to "delete"
* Delete button - deletes all webmentions from that source to all targets with the domain that was IndieAuth verified

**Comment by aaronpk** [comment]
![screenshot 2017-07-19 20 12 15](https://user-images.githubusercontent.com/113001/28398917-9b2028d0-6cbe-11e7-92e5-a3a75916a40a.png)

![screenshot 2017-07-19 20 13 21](https://user-images.githubusercontent.com/113001/28398928-b7fdf2ac-6cbe-11e7-801b-e4ec173490f6.png)

**Comment by tantek** [comment]
This looks amazing. Going to see if this is enough to build a likes facepile widget that can be quickly cleaned up by deleting specific webmentions.
