### ISSUE TITLE
webmention.io returns faulty links for all urls

### ISSUE THREAD

**Issue by diplix** [aaronpk/webmention.io#87]
[example](https://webmention.io/api/mentions?perPage=500&page=0&target[]=http://wirres.net/article/articleview/10450/1/6/):
```
    {
      "source": "https://brid-gy.appspot.com/comment/facebook/548616784/10154354494236785/10154354494236785_10154359699106785",
      "verified": true,
      "verified_date": "2016-12-29T10:36:06+00:00",
      "id": 408913,
      "private": false,
      "data": {
        "author": {
          "name": "Dave Kay",
          "url": "https://brid-gy.appspot.com/comment/facebook/548616784/10154354494236785/10154354494236785_10154359699106785",
          "photo": "https://brid-gy.appspot.com/comment/facebook/548616784/10154354494236785/10154354494236785_10154359699106785"
        },
        "url": "https://brid-gy.appspot.com/comment/facebook/548616784/10154354494236785/10154354494236785_10154359699106785",
        "name": null,
        "content": "Die ISP sind alle unverdächtig Altkunden pflegen zu wollen.",
        "published": "2016-12-29T10:31:52+00:00",
        "published_ts": 1483007512
      },
      "activity": {
        "type": "reply",
        "sentence": "Dave Kay commented '' on a post http://wirres.net/article/articleview/10450/1/6/",
        "sentence_html": "<a href=\"https://www.facebook.com/10207155716791935\">Dave Kay</a> commented '' on a post <a href=\"http://wirres.net/article/articleview/10450/1/6/\">http://wirres.net/article/articleview/10450/1/6/</a>"
      },
      "target": "http://wirres.net/article/articleview/10450/1/6/"
    },

```
source, data.author.url, data.author.photo and data.url are the same links to the bridgy-page. 
the icon url doesn’t work anymore and i can’t link back to the original facebook-comment or post. this is the case with almost all urls/webmentions i tested.

i saw it today for the first time, but i guess it happend a couple of days ago, after the webmention.io server crashed?

is there a way to get back the original data?

**Comment by aaronpk** [comment]
Thanks for catching this. I just launched the fix.

**Comment by diplix** [comment]
much better now, thanks. 
in the example above the `data.url` field now correctly reports a facebook url. [in a query of a newer post](https://webmention.io/api/mentions?perPage=500&page=0&target%5B%5D=http://wirres.net/article/articleview/10450/1/6/) all `data.url` fields are still bridgy links. maybe this will fix itself over time? or is it a bridgy-issue?

**Comment by aaronpk** [comment]
hm the old entries in my account were updated fine, this might be a different issue. Can you open a new issue with the URL of the particular one with the wrong URL? I'll look into it.
