### ISSUE TITLE
webmention.io catches bridgy links instead of real source links

### ISSUE THREAD

**Issue by diplix** [aaronpk/webmention.io#88]
[example query](https://webmention.io/api/mentions?perPage=500&page=0&target%5B%5D=http://wirres.net/article/articleview/10751/1/6/)

```
{
      "source": "https://brid-gy.appspot.com/like/facebook/548616784/10155060427196785/10205121118601536",
      "verified": true,
      "verified_date": "2017-08-19T15:54:34+00:00",
      "id": 452210,
      "private": false,
      "data": {
        "author": {
          "name": "Ron Maldonado",
          "url": "https://www.facebook.com/10205121118601536",
          "photo": "https://graph.facebook.com/v2.6/10205121118601536/picture?type=large"
        },
        "url": "https://brid-gy.appspot.com/like/facebook/548616784/10155060427196785/10205121118601536",
        "name": "tag:facebook.com,2013:10155060427196785_liked_by_10205121118601536\n  \n  \n  \n  \n      Ron Maldonado\n    \n    \n\n  https://www.facebook.com/548616784/posts/10155060427196785#liked-by-10205121118601536",
        "content": null,
        "published": null,
        "published_ts": null
      },
```
instead of
`        "url": "https://brid-gy.appspot.com/like/facebook/548616784/10155060427196785/10205121118601536",
`
it should be
`        "url": "https://www.facebook.com/548616784/10155060427196785/10205121118601536",
`

related to #87

--
corrected the example link above to the one i actually meant. the newest like/link in [the example](https://webmention.io/api/mentions?perPage=500&page=0&target%5B%5D=http://wirres.net/article/articleview/10751/1/6/) is actually correct again.

`        "url": "https://www.facebook.com/548616784/posts/10155060427196785#liked-by-997531380272085",
`

**Comment by snarfed** [comment]
Old one! I think this got fixed a while ago, @aaronpk maybe it can be closed?
