### ISSUE TITLE
since_id parameter (feature)

### ISSUE THREAD

**Issue by vrypan** [aaronpk/webmention.io#9]
It would be nice if /api/links supported a `since_id` parameter, in order to return links with id greater than `last_id`.

My use case: I have a static blog. I want to poll webmention.io periodically for mentions to my pages (using ?domain=). It would make my life much easier, and probably take some of the server load too, if I could ask for links with ID greater than the last ID I got last time I checked.

This is how twitter does it, see https://dev.twitter.com/docs/api/1.1/get/search/tweets and the `since_id` parameter.

**Comment by aaronpk** [comment]
This has been completed in 403ecf8842b4e48673af7fb17c82df385ae72eb9

**Comment by aaronpk** [comment]
@aarongustafson you may be interested in this for your Jekyll plugin

**Comment by aarongustafson** [comment]
Awesome! I will add it to the queue.

**Comment by aarongustafson** [comment]
Done.
