### ISSUE TITLE
Any interest in Atom support?

### ISSUE THREAD

**Issue by bdesham** [aaronpk/webmention.io#93]
I’m considering giving the `mentions` endpoint the option to return data in the Atom format. This would let you view your Webmention stream in a news reader. Assuming that the implementation is satisfactory, is this a change you would accept?

**Comment by aaronpk** [comment]
Hi @bdesham, actually the project is already supposed to have Atom support, but it looks like something about it broke! I'd be happy to accept a PR that fixes it! (I might also get around to fixing it as well, but I don't have an estimate of when I will get to it)

Here's where the Atom response is generated: https://github.com/aaronpk/webmention.io/blob/master/controllers/api.rb#L182

**Comment by bdesham** [comment]
I suspect that Atom support was broken in commit 2e230e4cd251a1f088efe5e71ff2c928a120c887. Just glancing at the source, it seems like the problem might be fixed by changing `link_array` on lines [188](https://github.com/aaronpk/webmention.io/blob/master/controllers/api.rb#L188) and [191](https://github.com/aaronpk/webmention.io/blob/master/controllers/api.rb#L191) to `links`. If I have time today I’ll try to get this project running locally to confirm that this fixes Atom support.

**Comment by bdesham** [comment]
I haven’t been 100% successful getting the project running locally. Is there any chance you could give me some sample data to manually insert into the `links` table? I believe that if I had that I could verify that my fix for this issue works. (If you want, you could just send me the data corresponding to my account, `esham.io`.)

**Comment by aaronpk** [comment]
Sure thing, I just emailed you a sql file!

**Comment by bdesham** [comment]
This issue is addressed in #99
