### ISSUE TITLE
API: Webmentions as HTML

### ISSUE THREAD

**Issue by sivy** [aaronpk/webmention.io#94]
It would be nice if in addition to the JSON representation delivered by the `https://webmention.io/api/mentions?jsonp=?` endpoint, we could request something like `https://webmention.io/api/mentions?html=?` and get unstyled HTML (with microformats, etc) ready to insert into a page.

This would be a boon to static sites like https://monkinetic.blog so that we don't have to write a lot of javascript rendering code.

**Comment by aaronpk** [comment]
This is now provided at a URL like `https://webmention.io/api/mentions.html`. It contains some basic styling, enough that it's readable if you view it. Everything is marked up with microformats so you can subscribe to this URL in a reader.
